// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloTransporta.src.Shared;

#nullable disable

namespace ModeloTransporta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413234830_CreateTypeVehicleTable")]
    partial class CreateTypeVehicleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ModeloTransporta.src.Modules.CompanyVehicle.Infrastructure.Entity.CompanyVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assignment_date");

                    b.Property<int>("companyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("company_vehicles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
