// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloTransporta.src.Shared;

#nullable disable

namespace ModeloTransporta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413235451_CreateVehicleStatusTable")]
    partial class CreateVehicleStatusTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ModeloTransporta.src.Modules.CompanyVehicle.Infrastructure.Entity.CompanyVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assignment_date");

                    b.Property<int>("companyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TypeVehicle.Infrastructure.Entity.TypeVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("capacityKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<decimal>("capacityM3")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity_m3");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.VehicleStatus.Infrastructure.Entity.VehicleStatusEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("vehicles_status", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
