// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloTransporta.src.Shared;

#nullable disable

namespace ModeloTransporta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414001349_CreateLoadDetailTable")]
    partial class CreateLoadDetailTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ModeloTransporta.src.Modules.CompanyVehicle.Infrastructure.Entity.CompanyVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assignment_date");

                    b.Property<int>("companyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.DocumentVehicle.Infrastructure.Entity.DocumentVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("documentNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document_number");

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiration_date");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("typeDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("type_document_id");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.DriverVehicle.Infrastructure.Entity.DriverVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at");

                    b.Property<int>("driverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("drivers_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Load.Infrastructure.Entity.LoadEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("customerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("destinationAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("destination_address");

                    b.Property<string>("originAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origin_address");

                    b.Property<int>("typeLoadId")
                        .HasColumnType("int")
                        .HasColumnName("type_load_id");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volume");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("id");

                    b.ToTable("loads", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TypeLoad.Infrastructure.Entity.TypeLoadEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("type_load", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TypeVehicle.Infrastructure.Entity.TypeVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("capacityKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<decimal>("capacityM3")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity_m3");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Vehicle.Infrastructure.Entity.VehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brand");

                    b.Property<string>("chassisNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("chassis_number");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("engineNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("engine_number");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plate");

                    b.Property<int>("statusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("typeVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("type_vehicle_id");

                    b.Property<int>("year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.VehicleStatus.Infrastructure.Entity.VehicleStatusEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("vehicles_status", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
