// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModeloTransporta.src.Shared;

#nullable disable

namespace ModeloTransporta.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414011855_CreateCustomerTable")]
    partial class CreateCustomerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ModeloTransporta.src.Modules.Bid.Infrastructure.Entity.BidEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("driverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("estimatedDelivery")
                        .HasColumnType("datetime")
                        .HasColumnName("estimated_delivery");

                    b.Property<int>("loadId")
                        .HasColumnType("int")
                        .HasColumnName("load_id");

                    b.Property<int>("statusBidId")
                        .HasColumnType("int")
                        .HasColumnName("status_bid_id");

                    b.HasKey("id");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.City.Infrastructure.Entity.CityEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("stateId")
                        .HasColumnType("int")
                        .HasColumnName("state_id");

                    b.Property<string>("zipCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("id");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.CompanyVehicle.Infrastructure.Entity.CompanyVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignmentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("assignment_date");

                    b.Property<int>("companyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("company_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Country.Infrastructure.Entity.CountryEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("isoCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("iso_code");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("phoneCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("phone_code");

                    b.HasKey("id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Customer.Infrastructure.Entity.CustomerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("company_name");

                    b.Property<bool>("isFrequent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_frequent");

                    b.Property<int>("personId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.DocumentVehicle.Infrastructure.Entity.DocumentVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("documentNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document_number");

                    b.Property<DateTime>("expirationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expiration_date");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_url");

                    b.Property<int>("typeDocumentId")
                        .HasColumnType("int")
                        .HasColumnName("type_document_id");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("documents_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Driver.Infrastructure.Entity.DriverEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("experienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("licenseCategory")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_category");

                    b.Property<string>("licenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("license_number");

                    b.Property<int>("personId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.HasKey("id");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.DriverVehicle.Infrastructure.Entity.DriverVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at");

                    b.Property<int>("driverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("drivers_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Load.Infrastructure.Entity.LoadEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("customerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("destinationAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("destination_address");

                    b.Property<string>("originAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("origin_address");

                    b.Property<int>("typeLoadId")
                        .HasColumnType("int")
                        .HasColumnName("type_load_id");

                    b.Property<decimal>("volume")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("volume");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("id");

                    b.ToTable("loads", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.LoadDetail.Infrastructure.Entity.LoadDetailEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("loadId")
                        .HasColumnType("int")
                        .HasColumnName("load_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("specialInstructions")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("special_instructions");

                    b.Property<string>("unitMeasure")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit_measure");

                    b.HasKey("id");

                    b.ToTable("load_details", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.LoadImage.Infrastructure.Entity.LoadImageEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("loadId")
                        .HasColumnType("int")
                        .HasColumnName("load_id");

                    b.HasKey("id");

                    b.ToTable("load_images", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.LoadStatusHistory.Infrastructure.Entity.LoadStatusHistoryEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("changedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("changed_at");

                    b.Property<int>("changedById")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_id");

                    b.Property<int>("loadId")
                        .HasColumnType("int")
                        .HasColumnName("load_id");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status_name");

                    b.HasKey("id");

                    b.ToTable("load_status_history", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Person.Infrastructure.Entity.PersonEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<int>("cityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("statusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.PersonTransport.Infrastructure.Entity.PersonTransportEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("personId")
                        .HasColumnType("int")
                        .HasColumnName("person_id");

                    b.Property<string>("roleInTrip")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("role_in_trip");

                    b.Property<int>("tripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("id");

                    b.ToTable("person_transport", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Rating.Infrastructure.Entity.RatingEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("evaluatedId")
                        .HasColumnType("int")
                        .HasColumnName("evaluated_id");

                    b.Property<int>("evaluatorId")
                        .HasColumnType("int")
                        .HasColumnName("evaluator_id");

                    b.Property<int>("score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.Property<int>("tripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("id");

                    b.ToTable("ratings", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.ReturnLoadSuggestion.Infrastructure.Entity.ReturnLoadSuggestionEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("currentTripId")
                        .HasColumnType("int")
                        .HasColumnName("current_trip_id");

                    b.Property<decimal>("relevanceScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("relevance_score");

                    b.Property<DateTime>("suggestedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("suggested_at");

                    b.Property<int>("suggestedLoadId")
                        .HasColumnType("int")
                        .HasColumnName("suggested_load_id");

                    b.HasKey("id");

                    b.ToTable("return_load_suggestions", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.StateRegion.Infrastructure.Entity.StateRegionEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("countryId")
                        .HasColumnType("int")
                        .HasColumnName("country_id");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("states_regions", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.StatusBid.Infrastructure.Entity.StatusBidEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("status_bids", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TravelScale.Infrastructure.Entity.TravelScaleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("arrivalEstimated")
                        .HasColumnType("datetime")
                        .HasColumnName("arrival_estimated");

                    b.Property<DateTime>("departureActual")
                        .HasColumnType("datetime")
                        .HasColumnName("departure_actual");

                    b.Property<int>("sequence")
                        .HasColumnType("int")
                        .HasColumnName("sequence");

                    b.Property<int>("tripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("id");

                    b.ToTable("travel_scale", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Trip.Infrastructure.Entity.TripEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("driverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<int>("loadId")
                        .HasColumnType("int")
                        .HasColumnName("load_id");

                    b.Property<string>("manifestNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("manifest_number");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<decimal>("totalPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_price");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TripAssignment.Infrastructure.Entity.TripAssignmentEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at");

                    b.Property<int>("driverId")
                        .HasColumnType("int")
                        .HasColumnName("driver_id");

                    b.Property<bool>("isConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_confirmed");

                    b.Property<int>("tripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("id");

                    b.ToTable("trip_assignments", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TripStatusHistory.Infrastructure.Entity.TripStatusHistoryEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("locationCoords")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location_coords");

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status_name");

                    b.Property<int>("tripId")
                        .HasColumnType("int")
                        .HasColumnName("trip_id");

                    b.HasKey("id");

                    b.ToTable("trip_status_history", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TypeLoad.Infrastructure.Entity.TypeLoadEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("type_load", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.TypeVehicle.Infrastructure.Entity.TypeVehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("capacityKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity_kg");

                    b.Property<decimal>("capacityM3")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("capacity_m3");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("type_vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.Vehicle.Infrastructure.Entity.VehicleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("brand");

                    b.Property<string>("chassisNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("chassis_number");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("engineNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("engine_number");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("plate")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("plate");

                    b.Property<int>("statusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("typeVehicleId")
                        .HasColumnType("int")
                        .HasColumnName("type_vehicle_id");

                    b.Property<int>("year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("ModeloTransporta.src.Modules.VehicleStatus.Infrastructure.Entity.VehicleStatusEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("vehicles_status", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
