using Microsoft.EntityFrameworkCore;
using ModeloTransporta.src.Modules.TypeVehicle.Infrastructure.Entity;
using ModeloTransporta.src.Modules.VehicleStatus.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Vehicle.Infrastructure.Entity;
using ModeloTransporta.src.Modules.DocumentVehicle.Infrastructure.Entity;
using ModeloTransporta.src.Modules.CompanyVehicle.Infrastructure.Entity;
using ModeloTransporta.src.Modules.DriverVehicle.Infrastructure.Entity;
using ModeloTransporta.src.Modules.TypeLoad.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Load.Infrastructure.Entity;
using ModeloTransporta.src.Modules.LoadDetail.Infrastructure.Entity;
using ModeloTransporta.src.Modules.LoadImage.Infrastructure.Entity;
using ModeloTransporta.src.Modules.LoadStatusHistory.Infrastructure.Entity;
using ModeloTransporta.src.Modules.StatusBid.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Bid.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Trip.Infrastructure.Entity;
using ModeloTransporta.src.Modules.TripAssignment.Infrastructure.Entity;
using ModeloTransporta.src.Modules.TravelScale.Infrastructure.Entity;
using ModeloTransporta.src.Modules.TripStatusHistory.Infrastructure.Entity;
using ModeloTransporta.src.Modules.PersonTransport.Infrastructure.Entity;
using ModeloTransporta.src.Modules.ReturnLoadSuggestion.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Rating.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Country.Infrastructure.Entity;
using ModeloTransporta.src.Modules.StateRegion.Infrastructure.Entity;
using ModeloTransporta.src.Modules.City.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Person.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Driver.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Customer.Infrastructure.Entity;
using ModeloTransporta.src.Modules.PersonStatus.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Role.Infrastructure.Entity;
using ModeloTransporta.src.Modules.PersonRole.Infrastructure.Entity;
using ModeloTransporta.src.Modules.AuthCredential.Infrastructure.Entity;
using ModeloTransporta.src.Modules.AuthSession.Infrastructure.Entity;
using ModeloTransporta.src.Modules.DocumentCategory.Infrastructure.Entity;
using ModeloTransporta.src.Modules.TypeDocument.Infrastructure.Entity;
using ModeloTransporta.src.Modules.DocumentStatus.Infrastructure.Entity;
using ModeloTransporta.src.Modules.DocumentDriver.Infrastructure.Entity;
using ModeloTransporta.src.Modules.DocumentCustomer.Infrastructure.Entity;
using ModeloTransporta.src.Modules.RelationType.Infrastructure.Entity;
using ModeloTransporta.src.Modules.AssignmentRole.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Entity1.Infrastructure.Entity;
using ModeloTransporta.src.Modules.TransportCompany.Infrastructure.Entity;
using ModeloTransporta.src.Modules.CompanyStatus.Infrastructure.Entity;
using ModeloTransporta.src.Modules.CompanyDocument.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Plan.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Subscription.Infrastructure.Entity;
using ModeloTransporta.src.Modules.CreditWallet.Infrastructure.Entity;
using ModeloTransporta.src.Modules.Payment.Infrastructure.Entity;
using ModeloTransporta.src.Modules.PriceHistory.Infrastructure.Entity;
using ModeloTransporta.src.Modules.ChatRoom.Infrastructure.Entity;
using ModeloTransporta.src.Modules.ChatMessage.Infrastructure.Entity;   

namespace ModeloTransporta.src.Shared;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }
    public DbSet<TypeVehicleEntity> TypeVehicles => Set<TypeVehicleEntity>();
    public DbSet<VehicleStatusEntity> VehicleStatuses => Set<VehicleStatusEntity>();
    public DbSet<VehicleEntity> Vehicles => Set<VehicleEntity>();
    public DbSet<DocumentVehicleEntity> DocumentVehicles => Set<DocumentVehicleEntity>();
    public DbSet<CompanyVehicleEntity> CompanyVehicles => Set<CompanyVehicleEntity>();
    public DbSet<DriverVehicleEntity> DriverVehicles => Set<DriverVehicleEntity>();
    public DbSet<TypeLoadEntity> TypeLoads => Set<TypeLoadEntity>();
    public DbSet<LoadEntity> Loads => Set<LoadEntity>();
    public DbSet<LoadDetailEntity> LoadDetails => Set<LoadDetailEntity>();
    public DbSet<LoadImageEntity> LoadImages => Set<LoadImageEntity>();
    public DbSet<LoadStatusHistoryEntity> LoadStatusHistories => Set<LoadStatusHistoryEntity>();
    public DbSet<StatusBidEntity> StatusBids => Set<StatusBidEntity>();
    public DbSet<BidEntity> Bids => Set<BidEntity>();
    public DbSet<TripEntity> Trips => Set<TripEntity>();
    public DbSet<TripAssignmentEntity> TripAssignments => Set<TripAssignmentEntity>();
    public DbSet<TravelScaleEntity> TravelScales => Set<TravelScaleEntity>();
    public DbSet<TripStatusHistoryEntity> TripStatusHistories => Set<TripStatusHistoryEntity>();
    public DbSet<PersonTransportEntity> PersonTransports => Set<PersonTransportEntity>();
    public DbSet<ReturnLoadSuggestionEntity> ReturnLoadSuggestions => Set<ReturnLoadSuggestionEntity>();
    public DbSet<RatingEntity> Ratings => Set<RatingEntity>();
    public DbSet<CountryEntity> Countries => Set<CountryEntity>();
    public DbSet<StateRegionEntity> StateRegions => Set<StateRegionEntity>();
    public DbSet<CityEntity> Cities => Set<CityEntity>();
    public DbSet<PersonEntity> Persons => Set<PersonEntity>();
    public DbSet<DriverEntity> Drivers => Set<DriverEntity>();
    public DbSet<CustomerEntity> Customers => Set<CustomerEntity>();
    public DbSet<PersonStatusEntity> PersonStatuses => Set<PersonStatusEntity>();
    public DbSet<RoleEntity> Roles => Set<RoleEntity>();
    public DbSet<PersonRoleEntity> PersonRoles => Set<PersonRoleEntity>();
    public DbSet<AuthCredentialEntity> AuthCredentials => Set<AuthCredentialEntity>();
    public DbSet<AuthSessionEntity> AuthSessions => Set<AuthSessionEntity>();
    public DbSet<DocumentCategoryEntity> DocumentCategories => Set<DocumentCategoryEntity>();
    public DbSet<TypeDocumentEntity> TypeDocuments => Set<TypeDocumentEntity>();
    public DbSet<DocumentStatusEntity> DocumentStatuses => Set<DocumentStatusEntity>();
    public DbSet<DocumentDriverEntity> DocumentDrivers => Set<DocumentDriverEntity>();
    public DbSet<DocumentCustomerEntity> DocumentCustomers => Set<DocumentCustomerEntity>();
    public DbSet<RelationTypeEntity> RelationTypes => Set<RelationTypeEntity>();
    public DbSet<AssignmentRoleEntity> AssignmentRoles => Set<AssignmentRoleEntity>();
    public DbSet<Entity1Entity> Entity1s => Set<Entity1Entity>();
    public DbSet<TransportCompanyEntity> TransportCompanies => Set<TransportCompanyEntity>();
    public DbSet<CompanyStatusEntity> CompanyStatuses => Set<CompanyStatusEntity>();
    public DbSet<CompanyDocumentEntity> CompanyDocuments => Set<CompanyDocumentEntity>();
    public DbSet<PlanEntity> Plans => Set<PlanEntity>();
    public DbSet<SubscriptionEntity> Subscriptions => Set<SubscriptionEntity>();
    public DbSet<CreditWalletEntity> CreditWallets => Set<CreditWalletEntity>();
    public DbSet<PaymentEntity> Payments => Set<PaymentEntity>();
    public DbSet<ChatRoomEntity> ChatRooms => Set<ChatRoomEntity>();
    public DbSet<PriceHistoryEntity> PriceHistories => Set<PriceHistoryEntity>();
    public DbSet<ChatMessageEntity> ChatMessages => Set<ChatMessageEntity>();


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new CompanyVehicleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new VehicleStatusEntityConfiguration());
        modelBuilder.ApplyConfiguration(new VehicleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DocumentVehicleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TypeVehicleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DriverVehicleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TypeLoadEntityConfiguration());
        modelBuilder.ApplyConfiguration(new LoadEntityConfiguration());
        modelBuilder.ApplyConfiguration(new LoadDetailEntityConfiguration());
        modelBuilder.ApplyConfiguration(new LoadImageEntityConfiguration());
        modelBuilder.ApplyConfiguration(new LoadStatusHistoryEntityConfiguration());
        modelBuilder.ApplyConfiguration(new StatusBidEntityConfiguration());
        modelBuilder.ApplyConfiguration(new BidEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TripEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TripAssignmentEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TravelScaleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TripStatusHistoryEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PersonTransportEntityConfiguration());
        modelBuilder.ApplyConfiguration(new ReturnLoadSuggestionEntityConfiguration());
        modelBuilder.ApplyConfiguration(new RatingEntityConfiguration());
        modelBuilder.ApplyConfiguration(new CountryEntityConfiguration());
        modelBuilder.ApplyConfiguration(new StateRegionEntityConfiguration());
        modelBuilder.ApplyConfiguration(new CityEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PersonEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DriverEntityConfiguration());
        modelBuilder.ApplyConfiguration(new CustomerEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PersonStatusEntityConfiguration());
        modelBuilder.ApplyConfiguration(new RoleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PersonRoleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new AuthCredentialEntityConfiguration());
        modelBuilder.ApplyConfiguration(new AuthSessionEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DocumentCategoryEntityConfiguration());
        modelBuilder.ApplyConfiguration(new TypeDocumentEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DocumentStatusEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DocumentDriverEntityConfiguration());
        modelBuilder.ApplyConfiguration(new DocumentCustomerEntityConfiguration());
        modelBuilder.ApplyConfiguration(new RelationTypeEntityConfiguration());
        modelBuilder.ApplyConfiguration(new AssignmentRoleEntityConfiguration());
        modelBuilder.ApplyConfiguration(new Entity1EntityConfiguration());
        modelBuilder.ApplyConfiguration(new TransportCompanyEntityConfiguration());
        modelBuilder.ApplyConfiguration(new CompanyStatusEntityConfiguration());     
        modelBuilder.ApplyConfiguration(new CompanyDocumentEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PlanEntityConfiguration());
        modelBuilder.ApplyConfiguration(new SubscriptionEntityConfiguration());
        modelBuilder.ApplyConfiguration(new CreditWalletEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PaymentEntityConfiguration());
        modelBuilder.ApplyConfiguration(new PriceHistoryEntityConfiguration());
        modelBuilder.ApplyConfiguration(new ChatRoomEntityConfiguration());
        modelBuilder.ApplyConfiguration(new ChatMessageEntityConfiguration());

        base.OnModelCreating(modelBuilder);
    }
}